version: "jpntaxi_base_v1.0.0"
# List of database versions and each yaml file consists of train/val/test splits
db_versions:
  - db_jpntaxigen2_v1
  - db_jpntaxigen2_v2
  - db_jpntaxi_v1
  - db_jpntaxi_v2
  - db_jpntaxi_v4